version: "3.7"

services:
  iotd:
    image: diamol/ch09-image-of-the-day
    ports:
      - "8088:80"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        failure_action: rollback
        monitor: 1m0s
        order: start-first
      rollback_config:
        parallelism: 4
        failure_action: continue
        order: start-first
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/image" ]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 30s
    networks:
      - app-net

  image-gallery:
    image: diamol/ch09-image-gallery
    ports:
      - "80:8000"
    networks:
      - app-net

  access-log:
    image: diamol/ch09-access-log
    networks:
      - app-net


networks:
  app-net:
    driver: overlay
